### PR TITLE
Add shadow package

### LINKED ISSUE #46: groupmod not available using trunk
Just tried out trunk for the new ARM builds. Unfortunately it fails at creating the user.

A quick search brought up the Alpine specific `adduser` command: https://wiki.alpinelinux.org/wiki/Setting_up_a_new_user

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...       
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...   
[cont-init.d] 10-adduser.sh: executing...                     
/var/run/s6/etc/cont-init.d/10-adduser.sh: line 26: groupmod: not found
/var/run/s6/etc/cont-init.d/10-adduser.sh: line 27: usermod: not found
id: unknown user abc
id: unknown user abc

Initializing container

User uid:
User gid:

chown: unknown user/group abc:abc                             
[cont-init.d] 10-adduser.sh: exited 1.                        
[cont-finish.d] executing container finish scripts...         
[cont-finish.d] done.
[s6-finish] waiting for services.                             
[s6-finish] sending all processes the TERM signal.            
[s6-finish] sending all processes the KILL signal and exiting.
```

### PR DESCRIPTION
**Pull request by chrisbanes**
Allows groupmod and usermod to work.

Fixes #46

### CODE REVIEW

**Comment by JakeWharton** [comment]
Thanks for looking at it. I was/am on vacation all week.

**Comment by JakeWharton** [comment]
Working?

**Comment by gc-ss** [comment]
@JakeWharton Feels like there's a regression.

Recommendation could be to be explicit with the `FROM golang:alpine AS build`  to `FROM golang:1.17.1-alpine …`

**Comment by gc-ss** [comment]
Is there a reason to have that `chown` instead of putting a helpful note for the user to run the appropriate command on their own system?

Eg: https://github.com/JakeWharton/docker-gphotos-sync/issues/43

The better solution would be to use the alpine native commands for `groupmod`, `usermod`

**Pull request merged**
